### ISSUE TITLE
Incorporación como miembro del equipo Podcast DevTech

### ISSUE THREAD

**Issue by margarita264** [lhidalgo27/devtech-podcast-web#2]
Hola Luciano
Abro este issue para relizar la practica grupal en tu proyecto Podcast Devtech.
Saludos! 🙂

**Comment by lhidalgo27** [comment]
hola margarita perfecto espero tus aportes =)

**Comment by margarita264** [comment]
Te mande mi propuesta cualquier duda me avisas

**Comment by lhidalgo27** [comment]
Gracias por tu aporte !! cierro el issue
